# Generated by Django 5.2 on 2025-06-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
    ]
