# Generated by Django 5.2 on 2025-06-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_alter_expense_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
    ]
