# Generated by Django 5.2 on 2025-06-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_alter_expense_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
