# Generated by Django 5.2 on 2025-06-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_alter_expense_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
    ]
